# Generated by Django 5.0.2 on 2024-02-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('password_hash', models.CharField(max_length=100)),
                ('role', models.CharField(default='basic', max_length=100)),
            ],
        ),
    ]
